const customEnvs = {
  NEXT_PUBLIC_CUSTOM_FOODIEE_REST_API:
    process.env.NEXT_PUBLIC_FOODIEE_SERVICES + '/api',
  NEXT_PUBLIC_CUSTOM_FOODIEE_GRAHPQL_API:
    process.env.NEXT_PUBLIC_FOODIEE_SERVICES + '/graphql',
};

export const {
  NEXT_PUBLIC_CUSTOM_FOODIEE_REST_API,
  NEXT_PUBLIC_CUSTOM_FOODIEE_GRAHPQL_API,
} = customEnvs;
